import { createClient } from "@/lib/supabase/server";

export const revalidate = 60;

export default async function ShowcasePage() {
  const supabase = createClient();

  const { data: captions } = await supabase
    .from("captions")
    .select("*, humor_flavors ( slug, description )")
    .order("created_datetime_utc", { ascending: false })
    .limit(100);

  const items = captions ?? [];

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 px-4 py-10">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-10">
          <h1 className="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
            Caption Showcase
          </h1>
          <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
            Captions generated by all student humor flavors
          </p>
        </div>

        {items.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-24 border-2 border-dashed border-zinc-200 dark:border-zinc-800 rounded-2xl text-center">
            <svg className="w-10 h-10 text-zinc-300 dark:text-zinc-700 mb-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
            </svg>
            <p className="font-medium text-zinc-500 dark:text-zinc-400">No captions yet</p>
            <p className="text-sm text-zinc-400 dark:text-zinc-500 mt-1">
              Generate captions from a flavor to see them here
            </p>
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2">
            {items.map((c) => {
              const flavor = c.humor_flavors as { slug: string; description: string } | null;
              return (
                <div
                  key={c.id}
                  className="p-5 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl hover:border-zinc-300 dark:hover:border-zinc-700 transition-colors flex flex-col gap-3"
                >
                  <p className="text-sm text-zinc-800 dark:text-zinc-200 leading-relaxed flex-1 whitespace-pre-wrap">
                    {c.content}
                  </p>
                  <div className="flex items-center justify-between flex-wrap gap-2 pt-2 border-t border-zinc-100 dark:border-zinc-800">
                    <span className="text-xs font-medium bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-400 px-2 py-0.5 rounded-md border border-indigo-200/50 dark:border-indigo-800/30">
                      {flavor?.slug ?? "unknown flavor"}
                    </span>
                    <div className="flex items-center gap-2.5">
                      {c.like_count > 0 && (
                        <span className="flex items-center gap-1 text-xs text-rose-500 dark:text-rose-400">
                          <svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor">
                            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
                          </svg>
                          {c.like_count}
                        </span>
                      )}
                      <span className="text-xs text-zinc-400 dark:text-zinc-500">
                        {new Date(c.created_datetime_utc).toLocaleDateString(undefined, {
                          month: "short", day: "numeric",
                        })}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
